### ISSUE TITLE
Default Root CSS values

### ISSUE THREAD

**Issue by DDuran19** [daedalus-developers/daedalus.codes#49]
this is to ensure that we will keep consistent theming all throughout our application.

Utility class
- [ ] max-width (to avoid relying to tailwind css for consistency, we must have a default utility class)
- [ ] button styles
- [ ] card styles
- [ ] hover effects

Root Variables

- [ ] --default-font-family
- [ ] --brand-font-family
- [ ] --emphasized-font-family
- [ ] --quotation-font-font-family

kindly suggest what else should we have as default

**Comment by directormac** [comment]
These are good points to have as a project as we expect to grow this, on  side note i have introduced the following variables in our tailwind configuration e.g the following from the global `app.css`
```css
/* Write your global styles here, in PostCSS syntax */
/* prettier-ignore */
@tailwind base;
/* prettier-ignore */
@tailwind components;
/* prettier-ignore */
@tailwind utilities;

:root {
	font-family: 'Inter Variable', sans-serif;
	--color-primary: #7209b7;
	--color-secondary: #8d62ef;
	--color-accent: #f72585;
	--color-surface: #ff8329;
	--color-daedalus-light: #ffffff;
	--color-daedalus-dark: #1d1d1f;
}

body {
	font-size: calc(15px + 0.45vw);
}

html.dark {
	color: white !important;
}
```
The following variables are closely related to the extending tailwind and bending it our way
```ts
import type { Config } from 'tailwindcss';
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';
import defaultTheme from 'tailwindcss/defaultTheme';

export default {
	content: ['./src/**/*.{html,js,svelte,ts}'],
	darkMode: 'class',
	theme: {
		extend: {
			colors: {
				primary: 'var(--color-primary)',
				secondary: 'var(--color-secondary)',
				accent: 'var(--color-accent)',
				surface: 'var(--color-surface)',
				daedalusLight: 'var(--color-daedalus-light)',
				daedalusDark: 'var(--color-daedalus-dark)'
			},
			fontFamily: {
				inter: ['Inter Variable', ...defaultTheme.fontFamily.sans]
			},
			backgroundSize: {
				'50%': '50%',
				'70%': '70%',
				'80%': '80%',
				'90%': '90%'
			},
			container: {
				center: true
			}
		}
	},
	plugins: [forms, typography]
} satisfies Config;
```
Enables us to call the `colors` and `fonts` we defined e.g
`bg-primary` `text-secondary` `border-accent` `bg-daedalusLight` , `font-inter` 

Also there is another way we can define a global class to extend tailwind's utility classes

on a CSS file we imported or a scoped style we can do the following just so we can utilize the classes provided by tailwind already

```css
div  {
  @apply min-w-4xl max-w-7xl bg-daedalusDark text-primary hover:text-secondary
}
```

The following should be the norm and should have been discussed before adapting tailwind, that was kind of my mistake without really onboarding everyone of its what if and how to utilize it

Read more about it [here](https://tailwindcss.com/docs/theme) and [here](https://tailwindcss.com/docs/configuration)
